[project]
name = "authwrap-client"
version = "0.1.0"
description = "Transparent authorization wrapper for any Python HTTP client."
authors = [{ name = "Your Name", email = "you@example.com" }]
dependencies = [
    "wrapt>=1.14.1"
]
requires-python = ">=3.8"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
